// src/App.svelte
<script>
  import { onMount } from 'svelte';
  import Mood from './components/Mood.svelte';
  import NotionConfig from './components/NotionConfig.svelte';
  import { isNotionConfigured, saveMoodToNotion } from './services/notion';

  // Define all available moods with their emojis
  const moods = [
    { id: 'angry', emoji: '😡', name: 'Angry' },
    { id: 'tired', emoji: '😴', name: 'Tired' },
    { id: 'stressed', emoji: '😰', name: 'Stressed' },
    { id: 'anxious', emoji: '😬', name: 'Anxious' },
    { id: 'calm', emoji: '😌', name: 'Calm' },
    { id: 'energetic', emoji: '⚡', name: 'Energetic' },
    { id: 'happy', emoji: '😄', name: 'Happy' }
  ];

  // State for selected mood and submission status
  let selectedMood = null;
  let submitted = false;
  let todayDate = '';
  let notionConfigured = false;
  let savingToNotion = false;
  let notionError = '';
  let showSettings = false;

  onMount(() => {
    // Format today's date
    const today = new Date();
    todayDate = today.toLocaleDateString('en-US', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    // Check if Notion is configured
    notionConfigured = isNotionConfigured();
  });

  function selectMood(mood) {
    selectedMood = mood;
  }

  async function submitMood() {
    if (!selectedMood) return;
    
    const today = new Date();
    
    // Save the mood selection
    const checkInData = {
      date: today.toISOString(),
      mood: selectedMood.id
    };
    
    // Store in localStorage
    const storedData = JSON.parse(localStorage.getItem('moodHistory') || '[]');
    storedData.push(checkInData);
    localStorage.setItem('moodHistory', JSON.stringify(storedData));
    
    // Try to save to Notion if configured
    if (notionConfigured) {
      try {
        savingToNotion = true;
        notionError = '';
        
        await saveMoodToNotion({
          mood: selectedMood.name,
          emoji: selectedMood.emoji,
          date: today
        });
        
        savingToNotion = false;
      } catch (error) {
        savingToNotion = false;
        notionError = `Failed to save to Notion: ${error.message}`;
        console.error('Error saving to Notion:', error);
      }
    }
    
    submitted = true;
  }
  
  function resetForm() {
    selectedMood = null;
    submitted = false;
    notionError = '';
  }

  function toggleSettings() {
    showSettings = !showSettings;
  }
</script>

<main class="main-container">
  <div class="container">
    <div class="header-container">
      <button class="settings-button" on:click={toggleSettings} title="Settings">
        ⚙️
      </button>
      <h1>Daily Mood Check-In</h1>
      <p class="date">{todayDate}</p>
    </div>

    {#if showSettings}
      <div class="settings-panel">
        <h2>Settings</h2>
        <NotionConfig />
        <button class="close-settings" on:click={toggleSettings}>Close Settings</button>
      </div>
    {:else}
      {#if !submitted}
        <div class="instructions">
          <p>How are you feeling today?</p>
          <p class="sub-text">Select the mood that best represents how you felt today.</p>
        </div>

        <div class="mood-grid">
          {#each moods as mood (mood.id)}
            <Mood 
              emoji={mood.emoji} 
              name={mood.name} 
              selected={selectedMood && selectedMood.id === mood.id}
              onSelect={() => selectMood(mood)} 
            />
          {/each}
        </div>

        <button 
          class="submit-button" 
          class:disabled={!selectedMood}
          disabled={!selectedMood || savingToNotion}
          on:click={submitMood}
        >
          {#if savingToNotion}
            Saving...
          {:else}
            Submit
          {/if}
        </button>

        {#if notionConfigured}
          <div class="notion-status">
            <span class="notion-badge">Notion Sync Enabled</span>
          </div>
        {/if}
      {:else}
        <div class="success-message">
          <div class="success-emoji">✅</div>
          <h2>Thanks for checking in!</h2>
          <p>You marked your mood today as:</p>
          <div class="selected-mood">
            <div class="large-emoji">{selectedMood.emoji}</div>
            <div class="mood-name">{selectedMood.name}</div>
          </div>

          {#if notionError}
            <div class="error-message">
              {notionError}
            </div>
          {:else if notionConfigured}
            <div class="notion-saved">
              ✅ Saved to Notion
            </div>
          {/if}

          <button class="reset-button" on:click={resetForm}>
            Check in again
          </button>
        </div>
      {/if}
    {/if}
  </div>
</main>

<style>
  .main-container {
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    padding: 20px;
  }

  .container {
    max-width: 600px;
    width: 100%;
    padding: 30px;
    background-color: white;
    border-radius: 16px;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
    text-align: center;
    position: relative; /* For absolute positioning of settings button */
  }

  .header-container {
    position: relative;
    margin-bottom: 20px;
    padding-top: 40px;
  }

  .settings-button {
    position: absolute;
    top: 0;
    right: 0;
    background: transparent;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
    padding: 5px;
  }

  .settings-panel {
    margin: 20px 0;
    text-align: left;
  }

  .close-settings {
    margin-top: 15px;
    padding: 10px 20px;
    background-color: #f1f1f1;
    color: #333;
    border: none;
    border-radius: 20px;
    cursor: pointer;
  }

  h1 {
    color: #333;
    margin-bottom: 5px;
  }

  .date {
    color: #666;
    margin-bottom: 10px;
    font-style: italic;
  }

  .instructions {
    margin-bottom: 20px;
  }

  .instructions p {
    margin: 5px 0;
  }

  .sub-text {
    color: #666;
    font-size: 0.9rem;
  }

  .mood-grid {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    margin: 30px 0;
  }

  .submit-button {
    padding: 12px 30px;
    background-color: #4a90e2;
    color: white;
    border: none;
    border-radius: 30px;
    font-size: 1rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s ease;
    min-width: 150px;
  }

  .submit-button:hover {
    background-color: #3a7bc8;
    transform: translateY(-2px);
    box-shadow: 0 4px 10px rgba(74, 144, 226, 0.3);
  }

  .submit-button.disabled {
    background-color: #ccc;
    cursor: not-allowed;
    transform: none;
    box-shadow: none;
  }

  .notion-status {
    margin-top: 15px;
    font-size: 0.8rem;
  }

  .notion-badge {
    background-color: #e8f5e9;
    color: #2e7d32;
    padding: 5px 10px;
    border-radius: 20px;
    font-size: 0.8rem;
  }

  .notion-saved {
    margin: 15px 0;
    color: #2e7d32;
    font-weight: 500;
  }

  .success-message {
    padding: 20px 0;
  }

  .success-emoji {
    font-size: 3rem;
    margin-bottom: 15px;
  }

  .selected-mood {
    margin: 20px 0;
  }

  .large-emoji {
    font-size: 5rem;
    margin-bottom: 10px;
  }

  .mood-name {
    font-size: 1.5rem;
    font-weight: 500;
  }

  .error-message {
    margin: 15px auto;
    background-color: #ffebee;
    color: #d32f2f;
    padding: 10px 15px;
    border-radius: 8px;
    max-width: 80%;
    font-size: 0.9rem;
  }

  .reset-button {
    margin-top: 20px;
    padding: 10px 20px;
    background-color: #f1f1f1;
    color: #333;
    border: none;
    border-radius: 20px;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .reset-button:hover {
    background-color: #e0e0e0;
  }

  /* Media queries for responsiveness */
  @media (max-width: 600px) {
    .main-container {
      padding: 0;
      display: block;
      overflow-y: auto;
      height: 100vh;
    }
    
    .container {
      max-width: 100%;
      width: 100%;
      min-height: 100vh;
      height: auto;
      padding: 20px;
      border-radius: 0;
      box-shadow: none;
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      overflow-y: visible;
      padding-top: 10px;
      padding-bottom: 40px;
    }
    
    .mood-grid {
      margin: 15px 0;
      flex-grow: 1;
      align-items: center;
    }
    
    h1 {
      margin-top: 0;
    }
    
    .submit-button {
      margin-bottom: 10px;
    }
    
    /* Ensure settings panel is scrollable on mobile */
    .settings-panel {
      max-height: 70vh;
      overflow-y: auto;
    }
  }
</style>

// src/app/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Mood from '@/components/Mood';
import NotionConfig from '@/components/NotionConfig';
import { isNotionConfigured, saveMoodToNotion } from '@/lib/notion';

interface MoodOption {
  id: string;
  emoji: string;
  name: string;
}

const moods: MoodOption[] = [
  { id: 'angry', emoji: '😡', name: 'Angry' },
  { id: 'tired', emoji: '😴', name: 'Tired' },
  { id: 'stressed', emoji: '😰', name: 'Stressed' },
  { id: 'anxious', emoji: '😬', name: 'Anxious' },
  { id: 'calm', emoji: '😌', name: 'Calm' },
  { id: 'energetic', emoji: '⚡', name: 'Energetic' },
  { id: 'happy', emoji: '😄', name: 'Happy' }
];

export default function Home() {
  const [selectedMood, setSelectedMood] = useState<MoodOption | null>(null);
  const [submitted, setSubmitted] = useState(false);
  const [todayDate, setTodayDate] = useState('');
  const [notionConfigured, setNotionConfigured] = useState(false);
  const [savingToNotion, setSavingToNotion] = useState(false);
  const [notionError, setNotionError] = useState('');
  const [showSettings, setShowSettings] = useState(false);

  useEffect(() => {
    // Format today's date
    const today = new Date();
    setTodayDate(today.toLocaleDateString('en-US', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    }));

    // Check if Notion is configured
    setNotionConfigured(isNotionConfigured());
  }, []);

  const selectMood = (mood: MoodOption) => {
    setSelectedMood(mood);
  };

  const submitMood = async () => {
    if (!selectedMood) return;
    
    const today = new Date();
    
    // Save the mood selection
    const checkInData = {
      date: today.toISOString(),
      mood: selectedMood.id
    };
    
    // Store in localStorage
    const storedData = JSON.parse(localStorage.getItem('moodHistory') || '[]');
    storedData.push(checkInData);
    localStorage.setItem('moodHistory', JSON.stringify(storedData));
    
    // Try to save to Notion if configured
    if (notionConfigured) {
      try {
        setSavingToNotion(true);
        setNotionError('');
        
        await saveMoodToNotion({
          mood: selectedMood.name,
          emoji: selectedMood.emoji,
          date: today
        });
        
        setSavingToNotion(false);
      } catch (error) {
        setSavingToNotion(false);
        setNotionError(`Failed to save to Notion: ${error instanceof Error ? error.message : 'Unknown error'}`);
        console.error('Error saving to Notion:', error);
      }
    }
    
    setSubmitted(true);
  };
  
  const resetForm = () => {
    setSelectedMood(null);
    setSubmitted(false);
    setNotionError('');
  };

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-2xl mx-auto px-4 py-8">
        <div className="bg-white">
          <div className="mb-8 flex flex-col items-center">
            <div className="w-full flex flex-row">
              <button
                onClick={() => setShowSettings(!showSettings)}
                className="p-2 text-2xl bg-transparent border-none cursor-pointer align"
                title="Settings"
              >
                ⚙️
              </button>
            </div>
            <h1 className="text-2xl font-bold text-center text-gray-800 mt-1">
              Daily Mood Check-In
            </h1>
            <p className="text-gray-600 text-center italic mt-2">{todayDate}</p>
          </div>

          {showSettings ? (
            <div className="settings-panel">
              <h2 className="text-xl font-semibold mb-4">Settings</h2>
              <NotionConfig />
              <button
                className="mt-4 px-4 py-2 bg-gray-200 text-gray-800 rounded hover:bg-gray-300 transition-colors"
                onClick={() => setShowSettings(false)}
              >
                Close Settings
              </button>
            </div>
          ) : !submitted ? (
            <>
              <div className="text-center mb-8">
                <p className="text-lg mb-2">How are you feeling today?</p>
                <p className="text-sm text-gray-600">
                  Select the mood that best represents how you felt today.
                </p>
              </div>

              <div className="flex flex-wrap justify-center gap-4 mb-8">
                {moods.map((mood) => (
                  <Mood
                    key={mood.id}
                    emoji={mood.emoji}
                    name={mood.name}
                    selected={selectedMood?.id === mood.id}
                    onSelect={() => selectMood(mood)}
                  />
                ))}
              </div>

              <div className="text-center">
                <button
                  className={`
                    px-8 py-3 rounded-full font-medium transition-all
                    ${selectedMood ? 'bg-blue-500 hover:bg-blue-600 text-white' : 'bg-gray-200 text-gray-500 cursor-not-allowed'}
                    ${savingToNotion ? 'opacity-75 cursor-wait' : ''}
                  `}
                  onClick={submitMood}
                  disabled={!selectedMood || savingToNotion}
                >
                  {savingToNotion ? 'Saving...' : 'Submit'}
                </button>

                {notionConfigured && (
                  <div className="mt-4">
                    <span className="inline-block px-3 py-1 bg-green-50 text-green-700 text-sm rounded-full">
                      Notion Sync Enabled
                    </span>
                  </div>
                )}
              </div>
            </>
          ) : (
            <div className="text-center">
              <div className="text-5xl mb-6">✅</div>
              <h2 className="text-2xl font-bold mb-4">Thanks for checking in!</h2>
              <p className="mb-4">You marked your mood today as:</p>
              <div className="mb-8">
                <div className="text-6xl mb-3">{selectedMood?.emoji}</div>
                <div className="text-xl font-medium">{selectedMood?.name}</div>
              </div>

              {notionError ? (
                <div className="mb-6 p-4 bg-red-50 text-red-700 rounded-lg">
                  {notionError}
                </div>
              ) : notionConfigured ? (
                <div className="mb-6 text-green-700 font-medium">
                  ✅ Saved to Notion
                </div>
              ) : null}

              <button
                className="px-6 py-2 bg-gray-200 text-gray-800 rounded-full hover:bg-gray-300 transition-colors"
                onClick={resetForm}
              >
                Check in again
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
