// src/components/NotionConfig.tsx
'use client';

import { useState, useEffect } from 'react';
import { initNotionClient, isNotionConfigured, clearNotionCredentials } from '../lib/notion';

export default function NotionConfig() {
  const [apiKey, setApiKey] = useState('');
  const [databaseId, setDatabaseId] = useState('');
  const [configured, setConfigured] = useState(false);
  const [showConfig, setShowConfig] = useState(false);
  const [configError, setConfigError] = useState('');
  const [configSuccess, setConfigSuccess] = useState('');

  useEffect(() => {
    // Check if already configured
    setConfigured(isNotionConfigured());
    
    // Try to load from localStorage
    setApiKey(localStorage.getItem('notion_api_key') || '');
    setDatabaseId(localStorage.getItem('notion_database_id') || '');
  }, []);

  const saveConfig = () => {
    if (!apiKey || !databaseId) {
      setConfigError('Both API Key and Database ID are required');
      return;
    }

    try {
      initNotionClient(apiKey, databaseId);
      setConfigured(true);
      setShowConfig(false);
      setConfigError('');
      setConfigSuccess('Notion API configured successfully!');
      
      // Hide success message after 3 seconds
      setTimeout(() => {
        setConfigSuccess('');
      }, 3000);
    } catch (error) {
      setConfigError(`Error configuring Notion API: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  };

  const resetConfig = () => {
    clearNotionCredentials();
    setApiKey('');
    setDatabaseId('');
    setConfigured(false);
    setConfigError('');
  };

  const toggleConfig = () => {
    setShowConfig(!showConfig);
  };

  return (
    <div className="my-5 p-4 rounded-lg bg-gray-50">
      {configSuccess && (
        <div className="mb-4 p-3 rounded bg-green-50 text-green-800 text-sm">
          {configSuccess}
        </div>
      )}
      
      {(!configured || showConfig) ? (
        <div className="text-left">
          <h3 className="text-lg font-semibold mb-2">Configure Notion API</h3>
          <p className="mb-5 text-sm text-gray-600">
            To save your moods to Notion, please provide your Notion API key and database ID.{' '}
            <a 
              href="https://developers.notion.com/docs/getting-started" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-blue-500 underline hover:text-blue-600"
            >
              Learn how to get these credentials
            </a>
          </p>
          
          {configError && (
            <div className="mb-4 p-3 rounded bg-red-50 text-red-700 text-sm">
              {configError}
            </div>
          )}
          
          <div className="mb-4">
            <label htmlFor="apiKey" className="block mb-1 font-medium">
              Notion API Key
            </label>
            <input
              type="password"
              id="apiKey"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              placeholder="secret_..."
              className="w-full p-2 border border-gray-300 rounded text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
          
          <div className="mb-4">
            <label htmlFor="databaseId" className="block mb-1 font-medium">
              Notion Database ID
            </label>
            <input
              type="text"
              id="databaseId"
              value={databaseId}
              onChange={(e) => setDatabaseId(e.target.value)}
              placeholder="a1b2c3d4-..."
              className="w-full p-2 border border-gray-300 rounded text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
          
          <div className="flex gap-2 mt-4">
            <button
              onClick={saveConfig}
              className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
            >
              Save Configuration
            </button>
            <button
              onClick={toggleConfig}
              className="px-4 py-2 bg-gray-200 text-gray-800 rounded hover:bg-gray-300 transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      ) : (
        <div className="flex items-center justify-between flex-wrap gap-4">
          <p className="font-medium">✅ Notion API configured</p>
          <div className="flex gap-2">
            <button
              onClick={toggleConfig}
              className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors"
            >
              Edit Configuration
            </button>
            <button
              onClick={resetConfig}
              className="px-4 py-2 bg-gray-200 text-gray-800 rounded hover:bg-gray-300 transition-colors"
            >
              Reset
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

// src/components/NotionConfig.svelte
<script>
  import { onMount } from 'svelte';
  import { initNotionClient, isNotionConfigured, clearNotionCredentials } from '../services/notion';

  let apiKey = '';
  let databaseId = '';
  let configured = false;
  let showConfig = false;
  let configError = '';
  let configSuccess = '';

  onMount(() => {
    // Check if already configured
    configured = isNotionConfigured();
    
    // Try to load from localStorage
    apiKey = localStorage.getItem('notion_api_key') || '';
    databaseId = localStorage.getItem('notion_database_id') || '';
  });

  function saveConfig() {
    if (!apiKey || !databaseId) {
      configError = 'Both API Key and Database ID are required';
      return;
    }

    try {
      // Initialize the Notion client with the provided credentials
      initNotionClient(apiKey, databaseId);
      configured = true;
      showConfig = false;
      configError = '';
      configSuccess = 'Notion API configured successfully!';
      
      // Hide success message after 3 seconds
      setTimeout(() => {
        configSuccess = '';
      }, 3000);
    } catch (error) {
      configError = `Error configuring Notion API: ${error.message}`;
    }
  }

  function resetConfig() {
    clearNotionCredentials();
    apiKey = '';
    databaseId = '';
    configured = false;
    configError = '';
  }

  function toggleConfig() {
    showConfig = !showConfig;
  }
</script>

<div class="notion-config">
  {#if configSuccess}
    <div class="success-message">{configSuccess}</div>
  {/if}
  
  {#if !configured || showConfig}
    <div class="config-form">
      <h3>Configure Notion API</h3>
      <p class="instructions">
        To save your moods to Notion, please provide your Notion API key and database ID.
        <a href="https://developers.notion.com/docs/getting-started" target="_blank" rel="noopener noreferrer">
          Learn how to get these credentials
        </a>
      </p>
      
      {#if configError}
        <div class="error-message">{configError}</div>
      {/if}
      
      <div class="form-group">
        <label for="apiKey">Notion API Key</label>
        <input type="password" id="apiKey" bind:value={apiKey} placeholder="secret_..." />
      </div>
      
      <div class="form-group">
        <label for="databaseId">Notion Database ID</label>
        <input type="text" id="databaseId" bind:value={databaseId} placeholder="a1b2c3d4-..." />
      </div>
      
      <div class="button-group">
        <button class="save-button" on:click={saveConfig}>Save Configuration</button>
        <button class="cancel-button" on:click={toggleConfig}>Cancel</button>
      </div>
    </div>
  {:else}
    <div class="config-status">
      <p>✅ Notion API configured</p>
      <div class="button-group">
        <button class="edit-button" on:click={toggleConfig}>Edit Configuration</button>
        <button class="reset-button" on:click={resetConfig}>Reset</button>
      </div>
    </div>
  {/if}
</div>

<style>
  .notion-config {
    margin: 20px 0;
    padding: 15px;
    border-radius: 8px;
    background-color: #f8f9fa;
  }

  .config-form {
    text-align: left;
  }

  h3 {
    margin-top: 0;
  }

  .instructions {
    margin-bottom: 20px;
    font-size: 0.9rem;
    color: #555;
  }
  
  .instructions a {
    color: #4a90e2;
    text-decoration: underline;
  }

  .form-group {
    margin-bottom: 15px;
  }

  label {
    display: block;
    margin-bottom: 5px;
    font-weight: 500;
  }

  input {
    width: 100%;
    padding: 8px 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 0.9rem;
  }

  .button-group {
    display: flex;
    gap: 10px;
    margin-top: 15px;
  }

  .save-button, .edit-button {
    background-color: #4a90e2;
    color: white;
    border: none;
    border-radius: 4px;
    padding: 8px 16px;
    cursor: pointer;
  }

  .cancel-button, .reset-button {
    background-color: #f1f1f1;
    color: #333;
    border: none;
    border-radius: 4px;
    padding: 8px 16px;
    cursor: pointer;
  }

  .error-message {
    background-color: #ffebee;
    color: #d32f2f;
    padding: 10px;
    margin-bottom: 15px;
    border-radius: 4px;
    font-size: 0.9rem;
  }

  .success-message {
    background-color: #e8f5e9;
    color: #2e7d32;
    padding: 10px;
    margin-bottom: 15px;
    border-radius: 4px;
    font-size: 0.9rem;
  }

  .config-status {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .config-status p {
    margin: 0;
    font-weight: 500;
  }

  @media (max-width: 600px) {
    .config-status {
      flex-direction: column;
      gap: 10px;
      align-items: flex-start;
    }
    
    .button-group {
      width: 100%;
      justify-content: center;
    }
  }
</style>
